defaults:
  run:
    working-directory: apis/poi/web
on: 
  push:
    branches: [master]
    paths: 
      - 'apis/poi/**'

name: Registry_Push_And_Deploy_DotNet

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    # checkout the repo
    - name: 'Checkout Github Action'
      uses: actions/checkout@master

    - uses: azure/docker-login@v1
      with:
        login-server: openhackgrb2e289acr.azurecr.io        
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - run: |
        docker build . -t openhackgrb2e289acr.azurecr.io/devopsoh/api-poi:${{ github.run_number }}
        docker push openhackgrb2e289acr.azurecr.io/devopsoh/api-poi:${{ github.run_number }} 

    - uses: azure/webapps-deploy@v2
      with:
       app-name: 'openhackgrb2e289poi'
       slot-name: 'staging'
       publish-profile: ${{ secrets.azureWebAppPublishProfile }}
       images: 'openhackgrb2e289acr.azurecr.io/devopsoh/api-poi:${{ github.run_number }}'
       
