defaults:
  run:
    working-directory: /apis/poi/web
on: 
  push:
    branches: [master]
    paths: /api/poi/**

name: Linux_Container_Node_Workflow

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    # checkout the repo
    - name: 'Checkout Github Action'
      uses: actions/checkout@master

    - uses: azure/docker-login@v1
      with:
        login-server: openhackrid7tdj5acr.azurecr.io        
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - run: |
        docker build . -t openhackrid7tdj5acr.azurecr.io/devopsoh/api-poi:${{ github.sha }}
        docker push openhackrid7tdj5acr.azurecr.io/devopsoh/api-poi:${{ github.sha }} 

    #- uses: azure/webapps-deploy@v2
    #with:
    #    app-name: 'node-rnc'
    #    publish-profile: ${{ secrets.azureWebAppPublishProfile }}
    #    images: 'contoso.azurecr.io/nodejssampleapp:${{ github.sha }}'
